### PR TITLE
Added mailgun driver support

### PR DESCRIPTION
**Pull request by alrik11es**
I've managed to add a driver for mailgun service. It's useful for cloud app deploying.

### CODE REVIEW

**Comment by alrik11es** [comment]
This class come from composer https://packagist.org/packages/mailgun/mailgun-php

Ok I'm adding this to the docs.

**Comment by WanWizard** [comment]
Eh, what I meant was https://github.com/fuel/docs/tree/1.8/develop/packages/email

At the very minimum the config should be documented.

**Comment by alrik11es** [comment]
Ouch! Sorry.
I'm adding it as soon as I can.

**Comment by WanWizard** [comment]
Thanks!

**Pull request merged**
