### PR TITLE
The character code of $header must be internal_encoding.

### PR DESCRIPTION
**Pull request by itcom**
https://github.com/fuel/email/commit/3a716cde8b3380ece33d649a0187794f074e123d

### CODE REVIEW

**Comment by WanWizard** [comment]
I am very much in doubt this is ok. The PHP manual says for `mb_language()`:

> Valid languages are "Japanese", "ja","English","en" and "uni" (UTF-8).

so this code will break most websites that are not in either English or Japanse, because the config value `language` contains a locale, like "pt_BR" for Brazilian Portuguese.

The internal encoding of the app will be set at startup using the config value `encoding`, which is set to "UTF-8" by default.

**Comment by itcom** [comment]
I understand.

Because it is a valid code only when setting invalid `charset`, I think that there is no problem.

**Comment by itcom** [comment]
https://github.com/php/php-src/blob/master/ext/mbstring/mbstring.c#L3724

**Comment by itcom** [comment]
However, since language should already be set, I think that this code itself is unnecessary.

**Comment by WanWizard** [comment]
You mean, just remove all the language business? And change it to:

````php
	protected function encode_mimeheader($header)
	{
		// we need mbstring for this
 		if ( ! MBSTRING)
 		{
 			throw new \RuntimeException('Email requires the multibyte package ("mbstring") package to be installed!');
 		}

		$transfer_encoding = ($this->config['encoding'] === 'quoted-printable') ? 'Q' : 'B' ;
		return mb_encode_mimeheader($header, $this->config['charset'], $transfer_encoding, $this>config['newline']);
	}
````

**Comment by itcom** [comment]
Yes. That's right.

**Pull request closed without merging**
