### PR TITLE
Return-Path was rendered usesless when used with sendmail. Fixed by usin...

### PR DESCRIPTION
**Pull request by antitoxic**
Return-Path was rendered usesless when used with `sendmail`. Fixed by using `Return-Path` as envelope sender if available.

The `-f` option will always override the stated in `Return-path` header and all notification/bounce emails will be send to the `To` header.

### CODE REVIEW

**Comment by WanWizard** [comment]
@FrenkyNet any comments?

**Comment by WanWizard** [comment]
@FrenkyNet ping?

**Comment by WanWizard** [comment]
Eh, merged to 1.3/develop? :grimacing: 

No worries, I'll cherry-pick to 1.5/develop.

**Comment by frankdejonge** [comment]
@WanWizard whoooooooooooops :/

**Comment by WanWizard** [comment]
No worries, fixed.

**Pull request merged**
