### PR TITLE
Big phpdoc fixes patch

### PR DESCRIPTION
**Pull request by SCIF**
Now you can use chaining normally by ide's autocompletion. Some other small phpdoc sugar. Fixed some typos.

### CODE REVIEW

**Comment by WanWizard** [comment]
There should not be a `@return static` in there, you only use that when the method returns `new static();`

**Comment by SCIF** [comment]
Just put it here — http://youtrack.jetbrains.com/issue/WI-16587

In fact «self» is not supported by most populars IDEs :( Netbeans and Aptana just ignores that setting like it's absent. Just will wait some desicion from IDEA. My suggestion — http://youtrack.jetbrains.com/issue/WI-16587#comment=27-583159

**Comment by frankdejonge** [comment]
I thought the correct formatting was @return $this ?

**Comment by WanWizard** [comment]
Nope, not according to the official PHPDOC docs. But most IDE's seem to use that.

**Comment by SCIF** [comment]
Ohm. Very interesting — https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#keyword

**Comment by SCIF** [comment]
Seems like php semantic ($this, static, self) will become phpdoc standart soon.

**Comment by WanWizard** [comment]
I think static and self are already in the standard, but $this isn't.

I would recommend to use `@return $this`, since most IDE's already support that, and the PHPDoc standard is in the making...

**Comment by SCIF** [comment]
Updated the commit (wow! git push -f works for existence pr).

**Pull request merged**
